import { XMarkdown } from '@ant-design/x-markdown';
import { Button, Card, Spin } from 'antd';
import React, { useEffect, useRef, useState } from 'react';

const FooterDemo = () => {
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const timer = useRef<NodeJS.Timeout | null>(null);

  const text = `
# AI Assistant Response

Hello! I'm your AI assistant.

I'm here to help you with various tasks.

Let me provide you with a comprehensive answer about how footer works in streaming scenarios.

## Key Features

- **Real-time Updates**: Footer updates as content streams
- **Loading Indicators**: Show processing status
- **Completion Status**: Display when content is fully loaded
- **Custom Styling**: Fully customizable appearance

This demonstrates how the footer parameter enhances the streaming experience.
  `;

  const startStreaming = () => {
    setLoading(true);
    setContent('');

    let currentIndex = 0;
    const streamInterval = setInterval(() => {
      if (currentIndex <= text.length) {
        setContent(text.slice(0, currentIndex));
        currentIndex += 2;
      } else {
        clearInterval(streamInterval);
        setLoading(false);
      }
    }, 30);

    timer.current = streamInterval;
  };

  const handleReRender = () => {
    if (timer.current) {
      clearInterval(timer.current);
    }
    startStreaming();
  };

  useEffect(() => {
    startStreaming();
    return () => {
      if (timer.current) {
        clearInterval(timer.current);
      }
    };
  }, []);

  return (
    <Card
      title="Footer Streaming Example"
      extra={<Button onClick={handleReRender}>Re-Render</Button>}
    >
      <XMarkdown
        content={content}
        footer={
          loading ? (
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '12px 0',
                borderTop: '1px solid #f0f0f0',
                marginTop: 16,
              }}
            >
              <Spin size="small" />
              <span>AI is thinking...</span>
            </div>
          ) : (
            <div
              style={{
                padding: '12px 0',
                borderTop: '1px solid #f0f0f0',
                color: '#666',
                fontSize: 12,
                marginTop: 16,
              }}
            >
              ✨ Response completed · Generated by AI Assistant
            </div>
          )
        }
        streaming={{ hasNextChunk: loading }}
      />
    </Card>
  );
};

export default FooterDemo;
