name: 🆇 Release to X

on:
  create

jobs:
  tweet:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    steps:
      - name: Tweet
        uses: nearform-actions/github-action-notify-twitter@master
        with:
          message: |
            🤖 Ant Design X just released @ant-design/x@${{ github.event.release.tag_name }} ✨🎊✨ Check out the full release note: ${{ github.event.release.html_url }}
          twitter-app-key: ${{ secrets.TWITTER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
